const USER = {
  LOGIN_NAME: 'LOGIN_NAME',
  MENU_LIST: 'MENU_LIST',
  REMEMBER_ME: 'REMEMBER_ME',
  AUTH_TOKEN: 'AUTH_TOKEN',
  // REFRESH_TOKEN: 'REFRESH_TOKEN',
  REDIRECT_URI: 'REDIRECT_URI'
}

export {
  USER
}
